// ---------------------------------------------------------------------------
// Funnel scale harness (O1–O3). Deterministic synthetic sources generated by
// the DuckDB CLI (seconds at 10M rows), uploaded to the lane object store and
// pushed through the REAL changelog → merge activities.
//
// Data model (version v ∈ {1, 2}), D = distinct keys = rows − dupRows:
//   rows i < D        → id = i + 1
//   rows i ≥ D (dups) → id = ((i − D) · 7919) mod D + 1     (appended last)
//   mid               = 'r<i>' — so the last-wins value is computable in JS
//   v2: ids with id mod 20 = 0 get mid 'r<i>-v2' (5 % changed) and
//       ids D+1 … D+⌈D/100⌉ are new (1 %).
// Columns are not in jsonb key order (the canonicalJson regression shape).
// ---------------------------------------------------------------------------

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";

export const ONTOLOGY_ID = "00000000-0000-0000-0000-000000000001";

export interface Dataset {
  rows: number;
  dupRows: number;
  distinct: number;
  newRows: number;
}

export function datasetShape(rows: number, dupRatio: number): Dataset {
  const dupRows = Math.floor(rows * dupRatio);
  const distinct = rows - dupRows;
  return { rows, dupRows, distinct, newRows: Math.ceil(distinct / 100) };
}

export function duckdbCli(): string {
  return process.env.TELLUS_DUCKDB_CLI ?? "/usr/local/bin/duckdb";
}

export function hasDuckdbCli(): boolean {
  try {
    execFileSync(duckdbCli(), ["--version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

export function generateCsv(file: string, ds: Dataset, version: 1 | 2): void {
  const D = ds.distinct;
  if (D % 7919 === 0) throw new Error("distinct key count must be coprime with 7919");
  const v2 = version === 2;
  const sql = `
    SET preserve_insertion_order = true;
    COPY (
      SELECT CASE WHEN id % 3 = 0 THEN 'open' WHEN id % 3 = 1 THEN 'closed' ELSE 'pending' END AS zeta_status,
             id,
             printf('%.2f', (id * 37 % 100000) / 10.0) AS alpha_amount,
             CASE WHEN ${v2 ? "true" : "false"} AND id % 20 = 0 THEN 'r' || i || '-v2' ELSE 'r' || i END AS mid,
             'payload-' || (id % 997) AS b
        FROM (
          SELECT i, CASE WHEN i < ${D} THEN i + 1 ELSE ((i - ${D}) * 7919) % ${D} + 1 END AS id
            FROM range(${ds.rows}) t(i)
          ${v2 ? `UNION ALL SELECT ${ds.rows} + j AS i, ${D} + j + 1 AS id FROM range(${ds.newRows}) t(j)` : ""}
        )
       ORDER BY i
    ) TO '${file.replace(/'/g, "''")}' (HEADER, DELIMITER ',');`;
  execFileSync(duckdbCli(), [":memory:"], { input: sql, stdio: ["pipe", "ignore", "inherit"] });
}

/** Expected last-wins `mid` for an id, mirroring generateCsv. */
export function expectedMid(ds: Dataset, id: number, version: 1 | 2): string | null {
  const D = ds.distinct;
  if (id > D) {
    if (version === 1 || id > D + ds.newRows) return null;
    const i = ds.rows + (id - D - 1);
    return id % 20 === 0 ? `r${i}-v2` : `r${i}`;
  }
  // Last dup row i ≥ D with ((i − D)·7919) mod D = id − 1, else row id − 1.
  let last = id - 1;
  const inv = modInverse(7919 % D, D);
  if (inv !== null && ds.dupRows > 0) {
    const k0 = Number((BigInt(id - 1) * BigInt(inv)) % BigInt(D)); // smallest k ≥ 0
    if (k0 < ds.dupRows) {
      const lastK = k0 + Math.floor((ds.dupRows - 1 - k0) / D) * D;
      last = D + lastK;
    }
  }
  return version === 2 && id % 20 === 0 ? `r${last}-v2` : `r${last}`;
}

function modInverse(a: number, m: number): number | null {
  if (m === 1) return 0;
  let [oldR, r] = [BigInt(a), BigInt(m)];
  let [oldS, s] = [1n, 0n];
  while (r !== 0n) {
    const q = oldR / r;
    [oldR, r] = [r, oldR - q * r];
    [oldS, s] = [s, oldS - q * s];
  }
  if (oldR !== 1n) return null;
  return Number(((oldS % BigInt(m)) + BigInt(m)) % BigInt(m));
}

export function sampleIds(ds: Dataset, version: 1 | 2, n = 400): number[] {
  const max = ds.distinct + (version === 2 ? ds.newRows : 0);
  const step = Math.max(1, Math.floor(max / n));
  const out: number[] = [];
  for (let id = 1; id <= max; id += step) out.push(id);
  out.push(max, 20, 40);
  return [...new Set(out)].filter((x) => x >= 1 && x <= max);
}

export interface ScaleType {
  apiName: string;
  objectTypeId: string;
  key: string;
}

type Db = typeof import("../../../src/db");
type Storage = typeof import("../../../src/services/storageService");

export async function createScaleType(db: Db, apiName: string, key: string): Promise<ScaleType> {
  const ot = await db.query(
    `INSERT INTO object_type (ontology_id, api_name, display_name, status)
     VALUES ($1, $2, $2, 'experimental') RETURNING object_type_id::text`,
    [ONTOLOGY_ID, apiName],
  );
  const objectTypeId = String(ot.rows[0].object_type_id);
  await db.query(
    `INSERT INTO backing_datasource (object_type_id, dataset_name, file_path, file_format, column_mapping, primary_key_column)
     VALUES ($1, $2, $3, 'csv', '{}'::jsonb, 'id')`,
    [objectTypeId, apiName.toLowerCase(), `${key}#foundry-dataset:${randomUUID()}#object-type:${objectTypeId}`],
  );
  return { apiName, objectTypeId, key };
}

export async function uploadCsv(storage: Storage, key: string, file: string): Promise<void> {
  const size = fs.statSync(file).size;
  await storage.uploadObject(key, fs.createReadStream(file), "text/csv", undefined, size);
}

export async function liveSnapshot(
  db: Db,
  apiName: string,
  ids: number[],
): Promise<{ count: number; mids: Map<number, string | null> }> {
  const c = await db.query(
    `SELECT count(*)::bigint AS n FROM object_instances WHERE ontology_id = $1 AND object_type_api_name = $2`,
    [ONTOLOGY_ID, apiName],
  );
  const r = await db.query(
    `SELECT primary_key, properties->>'mid' AS mid FROM object_instances
      WHERE ontology_id = $1 AND object_type_api_name = $2 AND primary_key = ANY($3::text[])`,
    [ONTOLOGY_ID, apiName, ids.map(String)],
  );
  const mids = new Map<number, string | null>(ids.map((i) => [i, null]));
  for (const row of r.rows) mids.set(Number(row.primary_key), String(row.mid));
  return { count: Number(c.rows[0].n), mids };
}

export function expectedSnapshot(ds: Dataset, version: 1 | 2, ids: number[]) {
  return {
    count: ds.distinct + (version === 2 ? ds.newRows : 0),
    mids: new Map(ids.map((i) => [i, expectedMid(ds, i, version)])),
  };
}

export async function cleanupScaleType(db: Db, storage: Storage, t: ScaleType | null, keyPrefix: string) {
  if (t) {
    const q = (sql: string, p: unknown[]) => db.query(sql, p).catch(() => undefined);
    await q(`DELETE FROM object_instances WHERE object_type_api_name = $1`, [t.apiName]);
    await q(`DELETE FROM merge_staging_instances WHERE object_type_api_name = $1`, [t.apiName]);
    await q(`DELETE FROM funnel_merge_bucket WHERE run_key LIKE $1`, [`${t.apiName}%`]);
    await q(`DELETE FROM funnel_state WHERE object_type_id = $1`, [t.objectTypeId]);
    await q(`DELETE FROM backing_datasource WHERE object_type_id = $1`, [t.objectTypeId]);
    await q(`DELETE FROM object_type WHERE object_type_id = $1`, [t.objectTypeId]);
  }
  await storage.deletePrefix(`${keyPrefix}/`).catch(() => undefined);
}

export function scaleRows(): number {
  return Number(process.env.TELLUS_SCALE_ROWS ?? 100_000);
}

export function workDir(name: string): string {
  const d = path.join(process.env.TELLUS_SCALE_WORKDIR ?? "/tmp/tellus-scale", name);
  fs.mkdirSync(d, { recursive: true });
  return d;
}

export function writeReport(name: string, report: unknown): string {
  const dir = process.env.TELLUS_SCALE_REPORT_DIR ?? "/tmp/tellus-scale/reports";
  fs.mkdirSync(dir, { recursive: true });
  const f = path.join(dir, `${name}.json`);
  fs.writeFileSync(f, `${JSON.stringify(report, null, 2)}\n`);
  return f;
}

/** Direct children of `pid` (Linux /proc; no pgrep dependency). */
export function childPids(pid: number): number[] {
  const out: number[] = [];
  for (const d of fs.readdirSync("/proc")) {
    if (!/^\d+$/.test(d)) continue;
    try {
      const stat = fs.readFileSync(`/proc/${d}/stat`, "utf8");
      const ppid = Number(stat.slice(stat.lastIndexOf(")") + 2).split(" ")[1]);
      if (ppid === pid) out.push(Number(d));
    } catch {
      /* raced exit */
    }
  }
  return out;
}

export const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
