/**
 * B10 — OSDK generator extension.
 *
 * Translates an `ObjectTypeWithBinding` into the OSDK source artefacts
 * (TypeScript class + property descriptors + Link Type descriptors) the
 * existing generator consumes. Invoked synchronously after binding creation
 * in-session; in production this lands as a job on the OSDK regen queue.
 */
import type {
  ObjectTypeWithBinding,
  ObjectProperty,
} from "../../ontology/contracts/object-type-with-binding";

export type OsdkExtensionOutput = {
  apiName: string;
  source: string;
  propertyDescriptors: Array<{ name: string; type: string; required: boolean; indexed: boolean }>;
  linkDescriptors: Array<{
    apiName: string;
    targetApiName: string;
    cardinality: "one-to-one" | "one-to-many" | "many-to-many";
  }>;
};

export function generateOsdkFromBinding(
  composite: ObjectTypeWithBinding,
  links: Array<{ apiName: string; targetApiName: string; cardinality: "one-to-one" | "one-to-many" | "many-to-many" }>,
): OsdkExtensionOutput {
  const apiName = composite.api_name;
  const propLines = composite.properties.map((p) => `  ${p.name}${p.required ? "" : "?"}: ${tsType(p)};`);
  const linkLines = links.map(
    (l) => `  ${l.apiName}: ${l.cardinality === "one-to-many" || l.cardinality === "many-to-many" ? `${l.targetApiName}[]` : l.targetApiName};`,
  );
  const source = [
    `// AUTO-GENERATED by B10 OSDK extension. Do not edit by hand.`,
    `import { ObjectSpec } from "@tellus/osdk";`,
    ``,
    `export interface ${apiName} extends ObjectSpec {`,
    ...propLines,
    ...linkLines,
    `}`,
    ``,
    `export const ${apiName}Descriptor = Object.freeze({`,
    `  apiName: ${JSON.stringify(apiName)},`,
    `  primaryKey: ${JSON.stringify(composite.binding?.pk_property ?? "id")},`,
    `  titleProperty: ${JSON.stringify(composite.binding?.title_property ?? null)},`,
    `  bindingRid: ${JSON.stringify(composite.binding?.rid ?? null)},`,
    `});`,
    ``,
  ].join("\n");

  return {
    apiName,
    source,
    propertyDescriptors: composite.properties.map((p) => ({
      name: p.name,
      type: p.type,
      required: p.required,
      indexed: p.indexed,
    })),
    linkDescriptors: links,
  };
}

function tsType(p: ObjectProperty): string {
  switch (p.type) {
    case "string":
    case "date":
    case "timestamp":
    case "decimal":
      return "string";
    case "int32":
    case "int64":
    case "float":
    case "double":
      return "number";
    case "boolean":
      return "boolean";
    case "json":
      return "unknown";
    default:
      return "unknown";
  }
}
