// ---------------------------------------------------------------------------
// Secret scanner for the evidence tree (audit #5/#6/#9).
//
// Walks a directory (default `.migration-evidence/`) and fails (exit 1) if
// ANY file matches a credential pattern. Runs in CI via
// tests/unit/evidence/evidenceAudit-unit.test.ts so committing credentials
// becomes a CI-visible failure.
//
// Allow-list rationale: Temporal history payload blobs are base64 strings
// that may start with "eyJ" but contain NO '.' separators — the JWT pattern
// below requires two literal dots, so payload blobs are not flagged. Nothing
// else is allow-listed: credentials are never acceptable, even test-fixture
// ones — redact (scripts/evidence/redact.ts) or remove them instead.
// ---------------------------------------------------------------------------

import fs from "fs";
import path from "path";

export interface SecretPattern {
  name: string;
  re: RegExp;
}

export interface SecretFinding {
  file: string;
  line: number;
  pattern: string;
  matchPreview: string;
}

export const SECRET_PATTERNS: SecretPattern[] = [
  { name: "jwt", re: /eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/ },
  { name: "bearer-token", re: /\bBearer\s+\S+/ },
  { name: "authorization-header", re: /Authorization\s*:/i },
  { name: "password", re: /password/i },
  { name: "passwd", re: /passwd/i },
  { name: "cookie", re: /cookie/i },
  { name: "session", re: /session(_id)?/i },
  { name: "secret", re: /secret/i },
  { name: "api-key", re: /api[_-]?key/i },
  { name: "private-key-block", re: /-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----/ },
  { name: "credentialed-postgres-url", re: /postgres(ql)?:\/\/[^/\s:@]+:[^@\s]+@/i },
  { name: "credentialed-mysql-url", re: /mysql:\/\/[^/\s:@]+:[^@\s]+@/i },
  { name: "aws-access-key", re: /AKIA[0-9A-Z]{16}/ },
];

// MANIFEST.json is generated by build-manifest.ts and contains only file
// digests, sizes, mtimes, and `git status --porcelain` PATHS (not contents).
// Scanning arbitrary repo file names for keywords like "session" (e.g. a doc
// named automate-session-*.md) is chronic false-positive territory and out of
// scope: secrets live in file CONTENTS, which the manifest has already hashed.
const SKIPPED_BASENAMES = new Set(["MANIFEST.json"]);

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.isFile() && !SKIPPED_BASENAMES.has(entry.name)) out.push(full);
  }
  return out;
}

export function scanFile(filePath: string): SecretFinding[] {
  const findings: SecretFinding[] = [];
  const content = fs.readFileSync(filePath, "utf8");
  const lines = content.split("\n");
  for (let i = 0; i < lines.length; i++) {
    for (const { name, re } of SECRET_PATTERNS) {
      const m = lines[i].match(re);
      if (m) {
        const preview = m[0].length > 40 ? `${m[0].slice(0, 37)}...` : m[0];
        findings.push({ file: filePath, line: i + 1, pattern: name, matchPreview: preview });
      }
    }
  }
  return findings;
}

export function scanDirectory(rootDir: string): SecretFinding[] {
  if (!fs.existsSync(rootDir)) return [];
  const findings: SecretFinding[] = [];
  for (const file of walk(rootDir)) findings.push(...scanFile(file));
  return findings;
}

if (require.main === module) {
  const rootDir = process.argv[2] ?? ".migration-evidence";
  const findings = scanDirectory(rootDir);
  if (findings.length === 0) {
    console.log(`scan-secrets: OK — no findings under ${rootDir}`);
  } else {
    console.error(`scan-secrets: ${findings.length} finding(s) under ${rootDir}:`);
    for (const f of findings) {
      console.error(`  ${f.file}:${f.line} [${f.pattern}] ${f.matchPreview}`);
    }
    process.exit(1);
  }
}
