// ---------------------------------------------------------------------------
// Action Execution Routes
//
// REST API endpoint for executing actions against the Ontology. This is the
// primary interface for action execution — all action executions go through
// this route.
//
// Mounted at: /api/v1/ontology/:ontologyId/actions
//
// Endpoints:
//   POST /:actionTypeApiName/apply      — Execute an action
//   POST /:actionTypeApiName/applyBatch — Bulk-execute an action (Task 25)
//   POST /:actionTypeApiName/validate   — Dry-run validation (no edits applied)
//
// The /validate and /applyBatch endpoints are also mounted at /api/v1/actions
// (without ontologyId) via the validateRouter and batchRouter exports. In
// that case, the default ontology is used automatically.
// ---------------------------------------------------------------------------

import crypto from "crypto";
import { Router, Request, Response, NextFunction } from "express";
import { executeAction } from "../actions/actionExecutor";
import {
  mapApplyExecutionToHttp,
  assertApplyOutcomeInvariant,
  collectPendingAcks,
  assertBatchAckOutcomeInvariant,
  COMMITTED_INDEX_PENDING,
  perItemAckBudgetMs,
  type BatchAckCandidate,
} from "../actions/linkIndexAckHttp";
import {
  validateAction,
  getDefaultOntologyId,
} from "../actions/actionValidator";
// FailureType import removed — executor now throws OntologyError directly
import { OntologyError } from "../utils/queryErrors";
import { resolveRequestTenant } from "../utils/requestTenant";
import {
  checkIdempotencyKey,
  storeIdempotencyKey,
  withIdempotencyLock,
} from "../actions/idempotency";
import { actionRateLimiter, batchRateLimiter } from "../middleware/rateLimiter";
import { planInlineEditBatch } from "../actions/inlineEditBatch";
import { sendError } from "../utils/responseFormatter";
import { query } from "../db";

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

const router = Router({ mergeParams: true });

/**
 * Preserve the request-level trace ID for every action execution in a batch.
 * The correlation middleware normally populates `req.correlationId`; reading
 * the header as a fallback keeps this router safe when mounted independently.
 */
function requestCorrelationId(req: Request): string | undefined {
  const fromMiddleware = (req as { correlationId?: unknown }).correlationId;
  if (typeof fromMiddleware === "string" && fromMiddleware.trim()) {
    return fromMiddleware;
  }
  const fromHeader = req.headers["x-correlation-id"];
  if (typeof fromHeader === "string" && fromHeader.trim()) {
    return fromHeader;
  }
  // Rwanda QA §3.6 — the platform-wide propagation header generated by
  // tellus-fe at action submission.
  const tellusHeader = req.headers["x-tellus-correlation-id"];
  return typeof tellusHeader === "string" && tellusHeader.trim()
    ? tellusHeader
    : undefined;
}

// ---------------------------------------------------------------------------
// POST /:actionTypeApiName/apply — Execute an action
// ---------------------------------------------------------------------------

router.post(
  "/:actionTypeApiName/apply",
  actionRateLimiter,
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const { ontologyId, actionTypeApiName } = req.params;
      const { parameters = {} } = req.body || {};

      if (!ontologyId) {
        throw new OntologyError(
          "ontologyId is required",
          "INVALID_PARAMETER",
          undefined,
          { parameterName: "ontologyId" }
        );
      }

      if (!actionTypeApiName) {
        throw new OntologyError(
          "actionTypeApiName is required",
          "INVALID_PARAMETER",
          undefined,
          { parameterName: "actionTypeApiName" }
        );
      }

      // ---------------------------------------------------------------
      // Idempotency (Task 21, Phase A5 F-04)
      //
      // If the client supplied an `Idempotency-Key` header we must:
      //   1. Serialize concurrent requests for that key (advisory lock).
      //   2. Re-check the cache inside the lock — a concurrent first
      //      winner may have just cached a result.
      //   3. Execute the action.
      //   4. Cache the result (success or error) before releasing.
      //
      // Without step 1, two requests that arrive inside a ~1ms window
      // both miss the cache, both execute, both cache — F-04 exactly.
      // The advisory lock turns the window into a queue: the loser
      // wakes on step 2 and returns the cached result.
      // ---------------------------------------------------------------
      const idempotencyKey = req.headers["idempotency-key"] as
        | string
        | undefined;

      // Optimistic concurrency: validate $expectedVersion early (Task 22)
      let expectedVersion: number | undefined;
      if (req.body?.$expectedVersion !== undefined) {
        const ev = Number(req.body.$expectedVersion);
        if (!Number.isInteger(ev) || ev < 0) {
          throw new OntologyError(
            "$expectedVersion must be a non-negative integer",
            "INVALID_PARAMETER",
            undefined,
            { parameterName: "$expectedVersion" }
          );
        }
        expectedVersion = ev;
      }

      // Extract execution context from request
      //
      // Phase 6.1 — thread the `req.security` (markings / cbac /
      // systemPrincipal / markingBypass) populated by the global
      // `securityContext` middleware into the executor so Stage 1c
      // can evaluate the CBAC policy on the action_type row's
      // allowed_principals / denied_principals / required_markings
      // columns (migration 037). Missing req.security → backward-compat
      // (gate skipped; matches pre-Phase-6.1 behaviour).
      const sec = (req as any).security as
        | {
            userId: string;
            markings: string[];
            cbac: string[];
            systemPrincipal: boolean;
            markingBypass: boolean;
          }
        | undefined;
      const context = {
        executedBy: (req as any).user?.id || "system",
        // The correlation middleware preserves a caller-provided value in
        // req.correlationId. Read the header as a fallback for route-level
        // tests and deployments that mount this router before that middleware.
        correlationId: requestCorrelationId(req),
        tenant: resolveRequestTenant(req),
        sourceIp:
          (req.headers["x-forwarded-for"] as string)?.split(",")[0]?.trim() ||
          req.socket.remoteAddress ||
          null,
        branchId: req.body?.branchId || null,
        expectedVersion,
        roles: (req as any).user?.roles || [],
        groups: (req as any).user?.groups || [],
        ...(sec
          ? {
              subjectKind: (sec.systemPrincipal ? "service" : "user") as
                | "user"
                | "service"
                | "token"
                | "anonymous",
              subjectIdentifier: sec.userId || (req as any).user?.id || "anonymous",
              subjectMarkings: sec.markings ?? [],
              subjectCbac: sec.cbac ?? [],
              markBypass: sec.markingBypass === true,
            }
          : {}),
      };

      // Core execute+store closure. Runs EITHER bare (no idempotency key)
      // OR under a session-level advisory lock (with a key). Both paths
      // share the same body so that on a cache-hit inside the lock we
      // still produce the cached response to the client.
      const doExecute = async () => {
        // Step 2: cache re-check inside the lock (or first check if no lock).
        if (idempotencyKey) {
          const cached = await checkIdempotencyKey(
            idempotencyKey,
            actionTypeApiName,
          );
          if (cached) {
            const { _httpStatus, _isError, ...body } = cached as {
              _httpStatus: number;
              _isError: boolean;
              [key: string]: unknown;
            };
            const status =
              typeof _httpStatus === "number" ? _httpStatus : 200;
            res.setHeader("X-Idempotency-Cached", "true");
            res.status(status).json(body);
            return;
          }
        }

        try {
          // Step 3: execute the action
          const result = await executeAction(
            ontologyId,
            actionTypeApiName,
            parameters,
            context,
          );

          // OSv2 read-after-write verdict (linkIndexAck, only present when
          // LINK_INDEX_ACK_REQUIRED=true and link edits were staged):
          //   confirmed/absent → 200 success body (byte-compatible);
          //   committed but NOT confirmed by the deadline →
          //   202 COMMITTED_INDEX_PENDING + executionId + pollable
          //   statusUrl. A post-commit link-index deferral is NEVER a
          //   client-visible failure — the mapper enforces that invariant
          //   (see actions/linkIndexAckHttp.ts).
          const outcome = mapApplyExecutionToHttp(result);
          assertApplyOutcomeInvariant(outcome);

          // Step 4a: cache success
          if (idempotencyKey) {
            await storeIdempotencyKey(
              idempotencyKey,
              actionTypeApiName,
              result.executionId,
              { _httpStatus: outcome.status, _isError: false, ...outcome.body },
            );
          }

          res.status(outcome.status).json(outcome.body);

          // NOTE: real-time object-change notifications are owned
          // exclusively by the action executor (actionExecutor
          // Stage 7, declarative and function branches), which
          // emits exactly one event per affected object type AFTER
          // the edit transaction commits — for /apply, /applyBatch,
          // and the bulk runner alike. This route previously emitted
          // a second, route-level copy on /apply only; that produced
          // duplicate events for every mutation and was removed.
          // Do not re-add emission here (pinned by
          // tests/unit/actions/actionExecutorFunctionEvents-unit.test.ts).
        } catch (err: unknown) {
          // Step 4b: cache error (same key → same error on retry)
          if (err instanceof OntologyError && idempotencyKey) {
            const errorBody = err.toResponse();
            const execId =
              (err.parameters?.executionId as string) ||
              crypto.randomUUID();
            await storeIdempotencyKey(
              idempotencyKey,
              actionTypeApiName,
              execId,
              {
                _httpStatus: err.statusCode,
                _isError: true,
                ...errorBody,
              },
            );
          }
          throw err;
        }
      };

      if (idempotencyKey) {
        await withIdempotencyLock(idempotencyKey, doExecute);
      } else {
        await doExecute();
      }
    } catch (err: any) {
      next(err);
    }
  }
);

// ---------------------------------------------------------------------------
// POST /:actionTypeApiName/applyBatch — Bulk action execution (Task 25)
//
// Executes the same action type multiple times with different parameter sets
// in a single API call. Each request in the batch is independent — if one
// fails, the others still succeed. This matches Palantir's inline edit
// behavior where each cell edit is independent and they are applied
// sequentially.
//
// Limits:
//   - Maximum 100 requests per batch
//   - Total affected objects across the batch cannot exceed 100,000
// ---------------------------------------------------------------------------

const MAX_BATCH_SIZE = 100;
const MAX_BATCH_AFFECTED_OBJECTS = 100_000;

router.post(
  "/:actionTypeApiName/applyBatch",
  batchRateLimiter,
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const { ontologyId, actionTypeApiName } = req.params;
      const batchStartTime = Date.now();
      const batchId = crypto.randomUUID();

      if (!ontologyId) {
        throw new OntologyError(
          "ontologyId is required",
          "INVALID_PARAMETER",
          undefined,
          { parameterName: "ontologyId" }
        );
      }

      if (!actionTypeApiName) {
        throw new OntologyError(
          "actionTypeApiName is required",
          "INVALID_PARAMETER",
          undefined,
          { parameterName: "actionTypeApiName" }
        );
      }

      // Validate request body
      const body = req.body || {};
      if (!body.requests || !Array.isArray(body.requests)) {
        throw new OntologyError(
          "requests must be a non-empty array",
          "INVALID_PARAMETER",
          400,
          { parameterName: "requests" }
        );
      }

      if (body.requests.length === 0) {
        throw new OntologyError(
          "requests must be a non-empty array",
          "INVALID_PARAMETER",
          400,
          { parameterName: "requests" }
        );
      }

      if (body.requests.length > MAX_BATCH_SIZE) {
        throw new OntologyError(
          `Batch size ${body.requests.length} exceeds the maximum of ${MAX_BATCH_SIZE} requests`,
          "SCALE_LIMIT_EXCEEDED",
          400,
          {
            batchSize: body.requests.length,
            maxBatchSize: MAX_BATCH_SIZE,
          }
        );
      }

      // Validate each request has a parameters object
      for (let i = 0; i < body.requests.length; i++) {
        const item = body.requests[i];
        if (!item || typeof item !== "object") {
          throw new OntologyError(
            `requests[${i}] must be an object`,
            "INVALID_PARAMETER",
            400,
            { parameterName: `requests[${i}]` }
          );
        }
        if (item.parameters !== undefined && typeof item.parameters !== "object") {
          throw new OntologyError(
            `requests[${i}].parameters must be an object`,
            "INVALID_PARAMETER",
            400,
            { parameterName: `requests[${i}].parameters` }
          );
        }
      }

      // Idempotency (Task 21 pattern, same _httpStatus semantics as /apply).
      // A retried batch with the same key replays the cached outcome —
      // including a 202 COMMITTED_INDEX_PENDING — without re-executing any
      // item. The cache namespace `${actionTypeApiName}#applyBatch` keeps a
      // single key colliding between /apply and /applyBatch from falsely
      // replaying the wrong shape (the module's cross-action-type guard
      // then returns null → first-time execution, matching pre-existing
      // behaviour for keys that were never honored here).
      const idempotencyKey = req.headers["idempotency-key"] as
        | string
        | undefined;
      const batchCacheName = `${actionTypeApiName}#applyBatch`;

      // Core execute+store closure (same shape as /apply's doExecute).
      const doExecute = async () => {
        if (idempotencyKey) {
          const cached = await checkIdempotencyKey(
            idempotencyKey,
            batchCacheName,
          );
          if (cached) {
            const { _httpStatus, _isError, ...cachedBody } = cached as {
              _httpStatus: number;
              _isError: boolean;
              [key: string]: unknown;
            };
            const status =
              typeof _httpStatus === "number" ? _httpStatus : 200;
            res.setHeader("X-Idempotency-Cached", "true");
            res.status(status).json(cachedBody);
            return;
          }
        }

      // Execute each request sequentially (matches Palantir's inline edit behavior)
      const results: Array<Record<string, unknown>> = [];
      let successCount = 0;
      let failedCount = 0;
      let totalAffectedObjects = 0;
      const envAckTimeoutMs = Number(
        process.env.LINK_INDEX_ACK_TIMEOUT_MS ?? 5_000,
      );

      for (let i = 0; i < body.requests.length; i++) {
        const item = body.requests[i];
        const parameters = item.parameters || {};

        // Pre-defer the ack when the wire budget is nearly spent: an
        // item must be answered 202-per-item-pending, never left for
        // the timeout middleware to 504 AFTER its PG commit.
        const ackBudgetMs = perItemAckBudgetMs({
          localsDeadlineAt: (res.locals as Record<string, unknown>)
            .requestBudgetDeadlineAt,
          envAckTimeoutMs,
        });

        // Build execution context for this individual request. Preserve the
        // same role/CBAC/marking principal as single apply and the default-
        // ontology batch mount; otherwise role criteria fail only on this
        // ontology-scoped batch path.
        const secBatch = (req as any).security as
          | { userId: string; markings: string[]; cbac: string[]; systemPrincipal: boolean; markingBypass: boolean }
          | undefined;
        const context = {
          executedBy: (req as any).user?.id || "system",
          correlationId: requestCorrelationId(req),
          tenant: resolveRequestTenant(req),
          sourceIp:
            (req.headers["x-forwarded-for"] as string)?.split(",")[0]?.trim() ||
            req.socket.remoteAddress ||
            null,
          branchId: item.branchId || body.branchId || null,
          roles: (req as any).user?.roles || [],
          groups: (req as any).user?.groups || [],
          ...(ackBudgetMs !== undefined ? { ackBudgetMs } : {}),
          ...(secBatch
            ? {
                subjectKind: (secBatch.systemPrincipal ? "service" : "user") as "user" | "service" | "token" | "anonymous",
                subjectIdentifier: secBatch.userId || (req as any).user?.id || "anonymous",
                subjectMarkings: secBatch.markings ?? [],
                subjectCbac: secBatch.cbac ?? [],
                markBypass: secBatch.markingBypass === true,
              }
            : {}),
        };

        try {
          const result = await executeAction(
            ontologyId,
            actionTypeApiName,
            parameters,
            context
          );

          totalAffectedObjects += result.affectedObjects.length;

          // Check if total affected objects exceeds the batch limit.
          // The action has already been executed and committed at this point,
          // so we must record it as a success. Only skip remaining requests.
          if (totalAffectedObjects > MAX_BATCH_AFFECTED_OBJECTS) {
            successCount++;
            results.push({
              index: i,
              success: true,
              executionId: result.executionId,
              affectedObjects: result.affectedObjects,
              scaleLimitReached: true,
              // OSv2 read-after-write verdict (present only when
              // LINK_INDEX_ACK_REQUIRED=true and link edits were staged).
              ...(result.linkIndexAck
                ? { linkIndexAck: result.linkIndexAck }
                : {}),
              errorMessage:
                `Total affected objects across batch (${totalAffectedObjects}) exceeds ` +
                `the limit of ${MAX_BATCH_AFFECTED_OBJECTS}. Remaining requests skipped.`,
            });

            // Skip remaining requests — these were never executed
            for (let j = i + 1; j < body.requests.length; j++) {
              failedCount++;
              results.push({
                index: j,
                success: false,
                executionId: null,
                failureType: "scale_limit_skipped",
                errorMessage:
                  "Skipped: total affected objects limit reached by a prior request in the batch.",
              });
            }
            break;
          }

          successCount++;
          results.push({
            index: i,
            success: true,
            executionId: result.executionId,
            affectedObjects: result.affectedObjects,
            // OSv2 read-after-write verdict (present only when
            // LINK_INDEX_ACK_REQUIRED=true and link edits were staged).
            ...(result.linkIndexAck
              ? { linkIndexAck: result.linkIndexAck }
              : {}),
          });
        } catch (err: any) {
          failedCount++;
          // Extract failure details from OntologyError or generic error
          const executionId =
            err instanceof OntologyError
              ? (err.parameters?.executionId as string) || null
              : null;
          const failureType =
            err instanceof OntologyError
              ? mapErrorCodeToFailureType(err.code)
              : "unclassified";
          const errorMessage = err.message || "Unknown error";

          results.push({
            index: i,
            success: false,
            executionId,
            failureType,
            errorMessage,
          });
        }
      }

      const totalDurationMs = Date.now() - batchStartTime;

      // OSv2 read-after-write aggregation (single rule for all batch
      // surfaces — actions/linkIndexAckHttp.ts): the WHOLE response is
      // 202 result:COMMITTED_INDEX_PENDING iff ANY committed item's
      // edge-index ack is unconfirmed; each pending item carries its own
      // pollable statusUrl. An index deferral is NEVER a per-item failure
      // nor an error status — the items are already committed in PG and a
      // failure shape would invite retries of applied mutations.
      const pendingAcks = collectPendingAcks(
        results as Array<Record<string, unknown>> & BatchAckCandidate[],
      );
      if (pendingAcks.length > 0) {
        const urlByIndex = new Map(
          pendingAcks.map((p) => [p.index, p.statusUrl]),
        );
        for (const r of results) {
          const u = urlByIndex.get(r.index as number);
          if (u) r.statusUrl = u;
        }
      }
      const batchOutcome = {
        status: pendingAcks.length > 0 ? 202 : 200,
        pendingCount: pendingAcks.length,
        ...(pendingAcks.length > 0
          ? { result: COMMITTED_INDEX_PENDING }
          : {}),
      };
      assertBatchAckOutcomeInvariant(batchOutcome);

      const responseBody = {
        batchId,
        totalRequests: body.requests.length,
        successCount,
        failedCount,
        results,
        totalDurationMs,
        ...(batchOutcome.result ? { result: batchOutcome.result } : {}),
      };

      // Step 4a (batch idempotency): cache the outcome — a retry replays
      // the SAME status (a 202 stays a 202) without re-executing any item.
      if (idempotencyKey) {
        await storeIdempotencyKey(
          idempotencyKey,
          batchCacheName,
          batchId,
          {
            _httpStatus: batchOutcome.status,
            _isError: false,
            ...responseBody,
          },
        );
      }

      return res.status(batchOutcome.status).json(responseBody);
      };

      if (idempotencyKey) {
        await withIdempotencyLock(idempotencyKey, doExecute);
      } else {
        await doExecute();
      }
    } catch (err: any) {
      // Batch-level errors (invalid body, over limit) → 400 via error handler
      if (err instanceof OntologyError) return next(err);
      next(err);
    }
  }
);

/**
 * Map an OntologyError code to a FailureType string for batch result items.
 */
function mapErrorCodeToFailureType(code: string): string {
  switch (code) {
    case "ACTION_TYPE_NOT_FOUND":
      return "unclassified";
    case "INVALID_PARAMETER":
      return "invalid_parameter";
    case "OBJECT_NOT_FOUND":
      return "object_not_found";
    case "DUPLICATE_PRIMARY_KEY":
      return "duplicate_primary_key";
    case "SCALE_LIMIT_EXCEEDED":
      return "scale_limit";
    case "CONCURRENCY_CONFLICT":
      return "unclassified";
    default:
      return "unclassified";
  }
}

// ---------------------------------------------------------------------------
// POST /:actionTypeApiName/validate — Dry-run validation (no edits applied)
//
// Runs Stages 1, 2, and 4 of the execution pipeline without applying edits.
// Used by UIs to preview what an action will do before committing. Returns
// a preview of affected objects on success, or validation errors on failure.
// ---------------------------------------------------------------------------

router.post(
  "/:actionTypeApiName/validate",
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      // ontologyId may come from the URL (/api/v1/ontology/:ontologyId/actions)
      // or be resolved from the default ontology (/api/v1/actions)
      let ontologyId = req.params.ontologyId;
      const { actionTypeApiName } = req.params;

      if (!ontologyId) {
        const defaultId = await getDefaultOntologyId();
        if (!defaultId) {
          throw new OntologyError(
            "No ontology found in the system",
            "INTERNAL_ERROR"
          );
        }
        ontologyId = defaultId;
      }

      if (!actionTypeApiName) {
        throw new OntologyError(
          "actionTypeApiName is required",
          "INVALID_PARAMETER",
          undefined,
          { parameterName: "actionTypeApiName" }
        );
      }

      const { parameters = {} } = req.body || {};
      const context = {
        executedBy: (req as any).user?.id || "system",
        roles: (req as any).user?.roles || [],
        groups: (req as any).user?.groups || [],
      };

      const result = await validateAction(
        ontologyId,
        actionTypeApiName,
        parameters,
        context
      );

      if (result.valid) {
        return res.status(200).json({
          valid: true,
          preview: result.preview,
        });
      }

      // Action type not found → throw OntologyError for standardized 404
      const isNotFound = result.errors.some(
        (e) => e === "Action type not found"
      );
      if (isNotFound) {
        throw new OntologyError(
          `Action type '${actionTypeApiName}' not found`,
          "ACTION_TYPE_NOT_FOUND",
          undefined,
          { actionTypeApiName }
        );
      }

      // All other validation failures → 400 with { valid, errors }
      return res.status(400).json({
        valid: false,
        errors: result.errors,
      });
    } catch (err: any) {
      if (err instanceof OntologyError) return next(err);
      next(err);
    }
  }
);

// ---------------------------------------------------------------------------
// Validate-only router (mounted at /api/v1/actions — no ontologyId)
// ---------------------------------------------------------------------------

const validateRouter = Router({ mergeParams: true });

validateRouter.post(
  "/:actionTypeApiName/validate",
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const { actionTypeApiName } = req.params;

      const defaultId = await getDefaultOntologyId();
      if (!defaultId) {
        throw new OntologyError(
          "No ontology found in the system",
          "INTERNAL_ERROR"
        );
      }

      if (!actionTypeApiName) {
        throw new OntologyError(
          "actionTypeApiName is required",
          "INVALID_PARAMETER",
          undefined,
          { parameterName: "actionTypeApiName" }
        );
      }

      const { parameters = {} } = req.body || {};
      const context = {
        executedBy: (req as any).user?.id || "system",
        roles: (req as any).user?.roles || [],
        groups: (req as any).user?.groups || [],
      };

      const result = await validateAction(
        defaultId,
        actionTypeApiName,
        parameters,
        context
      );

      if (result.valid) {
        return res.status(200).json({
          valid: true,
          preview: result.preview,
        });
      }

      // Action type not found → throw OntologyError for standardized 404
      const isNotFound = result.errors.some(
        (e) => e === "Action type not found"
      );
      if (isNotFound) {
        throw new OntologyError(
          `Action type '${actionTypeApiName}' not found`,
          "ACTION_TYPE_NOT_FOUND",
          undefined,
          { actionTypeApiName }
        );
      }

      // All other validation failures → 400 with { valid, errors }
      return res.status(400).json({
        valid: false,
        errors: result.errors,
      });
    } catch (err: any) {
      if (err instanceof OntologyError) return next(err);
      next(err);
    }
  }
);

// ---------------------------------------------------------------------------
// Batch-only router (mounted at /api/v1/actions — no ontologyId)
//
// This allows clients to call POST /api/v1/actions/:actionTypeApiName/applyBatch
// without specifying the ontologyId in the URL. The default ontology is used.
// ---------------------------------------------------------------------------

const batchRouter = Router({ mergeParams: true });

batchRouter.post(
  "/:actionTypeApiName/applyBatch",
  batchRateLimiter,
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const { actionTypeApiName } = req.params;
      const batchStartTime = Date.now();
      const batchId = crypto.randomUUID();

      const defaultId = await getDefaultOntologyId();
      if (!defaultId) {
        throw new OntologyError(
          "No ontology found in the system",
          "INTERNAL_ERROR"
        );
      }

      if (!actionTypeApiName) {
        throw new OntologyError(
          "actionTypeApiName is required",
          "INVALID_PARAMETER",
          undefined,
          { parameterName: "actionTypeApiName" }
        );
      }

      // Validate request body
      const body = req.body || {};
      if (!body.requests || !Array.isArray(body.requests)) {
        throw new OntologyError(
          "requests must be a non-empty array",
          "INVALID_PARAMETER",
          400,
          { parameterName: "requests" }
        );
      }

      if (body.requests.length === 0) {
        throw new OntologyError(
          "requests must be a non-empty array",
          "INVALID_PARAMETER",
          400,
          { parameterName: "requests" }
        );
      }

      if (body.requests.length > MAX_BATCH_SIZE) {
        throw new OntologyError(
          `Batch size ${body.requests.length} exceeds the maximum of ${MAX_BATCH_SIZE} requests`,
          "SCALE_LIMIT_EXCEEDED",
          400,
          {
            batchSize: body.requests.length,
            maxBatchSize: MAX_BATCH_SIZE,
          }
        );
      }

      // Validate each request has a parameters object
      for (let i = 0; i < body.requests.length; i++) {
        const item = body.requests[i];
        if (!item || typeof item !== "object") {
          throw new OntologyError(
            `requests[${i}] must be an object`,
            "INVALID_PARAMETER",
            400,
            { parameterName: `requests[${i}]` }
          );
        }
        if (item.parameters !== undefined && typeof item.parameters !== "object") {
          throw new OntologyError(
            `requests[${i}].parameters must be an object`,
            "INVALID_PARAMETER",
            400,
            { parameterName: `requests[${i}].parameters` }
          );
        }
      }

      // Idempotency (Task 21 pattern, same _httpStatus semantics as
      // the ontology-scoped applyBatch above).
      const idempotencyKey = req.headers["idempotency-key"] as
        | string
        | undefined;
      const batchCacheName = `${actionTypeApiName}#applyBatch`;

      const doExecute = async () => {
        if (idempotencyKey) {
          const cached = await checkIdempotencyKey(
            idempotencyKey,
            batchCacheName,
          );
          if (cached) {
            const { _httpStatus, _isError, ...cachedBody } = cached as {
              _httpStatus: number;
              _isError: boolean;
              [key: string]: unknown;
            };
            const status =
              typeof _httpStatus === "number" ? _httpStatus : 200;
            res.setHeader("X-Idempotency-Cached", "true");
            res.status(status).json(cachedBody);
            return;
          }
        }

      // Execute each request sequentially
      const results: Array<Record<string, unknown>> = [];
      let successCount = 0;
      let failedCount = 0;
      let totalAffectedObjects = 0;
      const envAckTimeoutMs = Number(
        process.env.LINK_INDEX_ACK_TIMEOUT_MS ?? 5_000,
      );

      for (let i = 0; i < body.requests.length; i++) {
        const item = body.requests[i];
        const parameters = item.parameters || {};

        // Pre-defer the ack when the wire budget is nearly spent (see
        // the ontology-scoped applyBatch above): an item must be
        // answered 202-per-item-pending, never 504'd after its commit.
        const ackBudgetMs = perItemAckBudgetMs({
          localsDeadlineAt: (res.locals as Record<string, unknown>)
            .requestBudgetDeadlineAt,
          envAckTimeoutMs,
        });

        // Phase 6.1 — thread req.security into the batch context too
        // so the per-iteration executeAction call runs Stage 1c against
        // the same CBAC policy.
        const secBatch = (req as any).security as
          | {
              userId: string;
              markings: string[];
              cbac: string[];
              systemPrincipal: boolean;
              markingBypass: boolean;
            }
          | undefined;
        const context = {
          executedBy: (req as any).user?.id || "system",
          correlationId: requestCorrelationId(req),
          tenant: resolveRequestTenant(req),
          sourceIp:
            (req.headers["x-forwarded-for"] as string)?.split(",")[0]?.trim() ||
            req.socket.remoteAddress ||
            null,
          branchId: item.branchId || body.branchId || null,
          roles: (req as any).user?.roles || [],
          groups: (req as any).user?.groups || [],
          ...(ackBudgetMs !== undefined ? { ackBudgetMs } : {}),
          ...(secBatch
            ? {
                subjectKind: (secBatch.systemPrincipal
                  ? "service"
                  : "user") as "user" | "service" | "token" | "anonymous",
                subjectIdentifier: secBatch.userId || (req as any).user?.id || "anonymous",
                subjectMarkings: secBatch.markings ?? [],
                subjectCbac: secBatch.cbac ?? [],
                markBypass: secBatch.markingBypass === true,
              }
            : {}),
        };

        try {
          const result = await executeAction(
            defaultId,
            actionTypeApiName,
            parameters,
            context
          );

          totalAffectedObjects += result.affectedObjects.length;

          // Check if total affected objects exceeds the batch limit.
          // The action has already been executed and committed at this point,
          // so we must record it as a success. Only skip remaining requests.
          if (totalAffectedObjects > MAX_BATCH_AFFECTED_OBJECTS) {
            successCount++;
            results.push({
              index: i,
              success: true,
              executionId: result.executionId,
              affectedObjects: result.affectedObjects,
              scaleLimitReached: true,
              // OSv2 read-after-write verdict (present only when
              // LINK_INDEX_ACK_REQUIRED=true and link edits were staged).
              ...(result.linkIndexAck
                ? { linkIndexAck: result.linkIndexAck }
                : {}),
              errorMessage:
                `Total affected objects across batch (${totalAffectedObjects}) exceeds ` +
                `the limit of ${MAX_BATCH_AFFECTED_OBJECTS}. Remaining requests skipped.`,
            });

            // Skip remaining requests — these were never executed
            for (let j = i + 1; j < body.requests.length; j++) {
              failedCount++;
              results.push({
                index: j,
                success: false,
                executionId: null,
                failureType: "scale_limit_skipped",
                errorMessage:
                  "Skipped: total affected objects limit reached by a prior request in the batch.",
              });
            }
            break;
          }

          successCount++;
          results.push({
            index: i,
            success: true,
            executionId: result.executionId,
            affectedObjects: result.affectedObjects,
            // OSv2 read-after-write verdict (present only when
            // LINK_INDEX_ACK_REQUIRED=true and link edits were staged).
            ...(result.linkIndexAck
              ? { linkIndexAck: result.linkIndexAck }
              : {}),
          });
        } catch (err: any) {
          failedCount++;
          const executionId =
            err instanceof OntologyError
              ? (err.parameters?.executionId as string) || null
              : null;
          const failureType =
            err instanceof OntologyError
              ? mapErrorCodeToFailureType(err.code)
              : "unclassified";
          const errorMessage = err.message || "Unknown error";

          results.push({
            index: i,
            success: false,
            executionId,
            failureType,
            errorMessage,
          });
        }
      }

      const totalDurationMs = Date.now() - batchStartTime;

      // OSv2 read-after-write aggregation (single rule for all batch
      // surfaces — actions/linkIndexAckHttp.ts). Whole-batch 202 iff ANY
      // committed item's edge-index ack is unconfirmed; pending items
      // carry their own pollable statusUrl; a post-commit deferral is
      // NEVER an error status nor a per-item failure.
      const pendingAcks = collectPendingAcks(
        results as Array<Record<string, unknown>> & BatchAckCandidate[],
      );
      if (pendingAcks.length > 0) {
        const urlByIndex = new Map(
          pendingAcks.map((p) => [p.index, p.statusUrl]),
        );
        for (const r of results) {
          const u = urlByIndex.get(r.index as number);
          if (u) r.statusUrl = u;
        }
      }
      const batchOutcome = {
        status: pendingAcks.length > 0 ? 202 : 200,
        pendingCount: pendingAcks.length,
        ...(pendingAcks.length > 0
          ? { result: COMMITTED_INDEX_PENDING }
          : {}),
      };
      assertBatchAckOutcomeInvariant(batchOutcome);

      const responseBody = {
        batchId,
        totalRequests: body.requests.length,
        successCount,
        failedCount,
        results,
        totalDurationMs,
        ...(batchOutcome.result ? { result: batchOutcome.result } : {}),
      };

      if (idempotencyKey) {
        await storeIdempotencyKey(
          idempotencyKey,
          batchCacheName,
          batchId,
          {
            _httpStatus: batchOutcome.status,
            _isError: false,
            ...responseBody,
          },
        );
      }

      return res.status(batchOutcome.status).json(responseBody);
      };

      if (idempotencyKey) {
        await withIdempotencyLock(idempotencyKey, doExecute);
      } else {
        await doExecute();
      }
    } catch (err: any) {
      if (err instanceof OntologyError) return next(err);
      next(err);
    }
  }
);

// ---------------------------------------------------------------------------
// POST /inlineEditBatch — All-or-nothing bulk inline-edit submission (Pillar 3)
//
// Foundry: "edits will be submitted all at once and will succeed if they all
// pass parameter and global submission criteria for the corresponding object."
// "Actions will return an error if an inline edit attempts to edit the same
// object twice."
//
// This endpoint:
//   1. Plans the batch (validate, conflict-check, coalesce) via
//      planInlineEditBatch.
//   2. If any edit fails validation OR a conflict is detected → commit
//      nothing, return per-edit errors (HTTP 422).
//   3. If all pass → execute each coalesced edit sequentially via
//      executeAction. If a LATE execution failure occurs (network/race),
//      earlier commits stand but the response reports the failure — this
//      is an edge case that pre-validation should prevent.
// ---------------------------------------------------------------------------

router.post(
  "/inlineEditBatch",
  batchRateLimiter,
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const { ontologyId } = req.params;
      if (!ontologyId) {
        throw new OntologyError(
          "ontologyId is required",
          "INVALID_PARAMETER",
          undefined,
          { parameterName: "ontologyId" },
        );
      }

      const body = req.body || {};
      if (!body.edits || !Array.isArray(body.edits) || body.edits.length === 0) {
        throw new OntologyError(
          "edits must be a non-empty array",
          "INVALID_PARAMETER",
          400,
          { parameterName: "edits" },
        );
      }

      if (body.edits.length > MAX_BATCH_SIZE) {
        throw new OntologyError(
          `Batch size ${body.edits.length} exceeds the maximum of ${MAX_BATCH_SIZE} edits`,
          "SCALE_LIMIT_EXCEEDED",
          400,
          { batchSize: body.edits.length, maxBatchSize: MAX_BATCH_SIZE },
        );
      }

      // Resolve PK parameter names for each action referenced in the batch.
      // The client sends the actionApiName per edit (from the property's
      // ontology metadata); we look up the action's object_reference parameter
      // to construct the action's parameter object.
      const allActionNames: string[] = (body.edits as Array<{ actionApiName?: string }>)
        .map((e) => e.actionApiName)
        .filter((x: string | undefined): x is string => typeof x === "string" && x.length > 0);
      const actionApiNames = [...new Set<string>(allActionNames)];

      const pkParameterMap = new Map<string, string>();
      for (const actionApiName of actionApiNames) {
        const rows = await query(
          // Foundry parity: is_enabled is cosmetic — do not exclude rows
          // whose flag is false; apply-time guards handle real safety.
          `SELECT parameters FROM action_type
           WHERE ontology_id = $1 AND api_name = $2`,
          [ontologyId, actionApiName],
        );
        if (rows.rows.length === 0) {
          return sendError(
            res,
            "INLINE_EDIT_ACTION_NOT_FOUND",
            `Action type "${actionApiName}" was not found in this ontology.`,
          );
        }
        const params = rows.rows[0].parameters as Array<{ apiName: string; type: string }>;
        const pkParam = params.find((p) => p.type === "object_reference");
        if (!pkParam) {
          return sendError(
            res,
            "INLINE_EDIT_ACTION_INELIGIBLE",
            `Action type "${actionApiName}" has no object_reference parameter and cannot serve inline edits.`,
          );
        }
        pkParameterMap.set(actionApiName, pkParam.apiName as string);
      }

      // Plan the batch (pure: validate + conflict-check + coalesce).
      const plan = planInlineEditBatch(body.edits, pkParameterMap);

      // All-or-nothing: if any edit is invalid or a conflict exists, commit NOTHING.
      if (!plan.allValid || plan.conflicts.length > 0) {
        return res.status(422).json({
          batchId: crypto.randomUUID(),
          submitted: false,
          totalEdits: body.edits.length,
          results: plan.results,
          conflicts: plan.conflicts,
          error: "One or more edits failed validation. No edits were committed.",
        });
      }

      // Execute each coalesced edit sequentially.
      const results: Array<Record<string, unknown>> = [];
      let successCount = 0;
      let failedCount = 0;
      const context = {
        executedBy: (req as any).user?.id || "system",
        correlationId: requestCorrelationId(req),
        tenant: resolveRequestTenant(req),
        sourceIp:
          (req.headers["x-forwarded-for"] as string)?.split(",")[0]?.trim() ||
          req.socket.remoteAddress ||
          null,
        branchId: body.branchId || null,
      };

      for (let i = 0; i < plan.edits.length; i++) {
        const edit = plan.edits[i];
        try {
          const result = await executeAction(
            ontologyId,
            edit.actionApiName,
            edit.parameters,
            context,
          );
          successCount++;
          results.push({
            index: i,
            success: true,
            executionId: result.executionId,
            affectedObjects: result.affectedObjects,
            sourceIndices: edit.sourceIndices,
          });
        } catch (err: any) {
          failedCount++;
          results.push({
            index: i,
            success: false,
            executionId: err instanceof OntologyError
              ? (err.parameters?.executionId as string) || null
              : null,
            failureType: err instanceof OntologyError
              ? mapErrorCodeToFailureType(err.code)
              : "unclassified",
            errorMessage: err.message || "Unknown error",
            sourceIndices: edit.sourceIndices,
          });
        }
      }

      return res.status(failedCount > 0 ? 207 : 200).json({
        batchId: crypto.randomUUID(),
        submitted: true,
        totalEdits: body.edits.length,
        coalescedEdits: plan.edits.length,
        successCount,
        failedCount,
        results,
      });
    } catch (err: any) {
      if (err instanceof OntologyError) return next(err);
      next(err);
    }
  },
);

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export { validateRouter, batchRouter };
export default router;
