/**
 * totpService.ts
 * --------------
 * In-app TOTP (RFC 6238) enrollment + verification.
 *
 * Uses Node's built-in crypto — no external OTP dependency needed. The
 * secret is generated by tellus, stored in user_totp_secrets keyed on
 * the Keycloak sub, shown to the user once (as a QR code + otpauth URI),
 * and verified on every subsequent login step.
 *
 * RFC 6238 defaults: SHA-1, 30-second step, 6-digit code, ±1 step window.
 */

import crypto from 'crypto';
import qrcode from 'qrcode';
import type { Knex } from 'knex';
import { AppError } from '../utils/foundryAppError';

const RFC4648_BASE32 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

/** Encode a byte array as base32 without padding. */
function base32Encode(bytes: Buffer): string {
  let bits = 0;
  let value = 0;
  let out = '';
  for (const b of bytes) {
    value = (value << 8) | b;
    bits += 8;
    while (bits >= 5) {
      out += RFC4648_BASE32[(value >>> (bits - 5)) & 0x1f];
      bits -= 5;
    }
  }
  if (bits > 0) out += RFC4648_BASE32[(value << (5 - bits)) & 0x1f];
  return out;
}

function base32Decode(input: string): Buffer {
  const cleaned = input.replace(/=/g, '').toUpperCase();
  const bytes: number[] = [];
  let bits = 0;
  let value = 0;
  for (const ch of cleaned) {
    const idx = RFC4648_BASE32.indexOf(ch);
    if (idx === -1) throw new Error(`invalid base32 char: ${ch}`);
    value = (value << 5) | idx;
    bits += 5;
    if (bits >= 8) {
      bytes.push((value >>> (bits - 8)) & 0xff);
      bits -= 8;
    }
  }
  return Buffer.from(bytes);
}

/** Generate a fresh 20-byte secret, returned as a base32 string. */
function generateBase32Secret(): string {
  return base32Encode(crypto.randomBytes(20));
}

/** RFC 6238 HOTP for a given counter. Used by both generate and verify. */
function hotpAt(base32Secret: string, counter: number): string {
  const key = base32Decode(base32Secret);
  const buf = Buffer.alloc(8);
  buf.writeUInt32BE(Math.floor(counter / 0x100000000), 0);
  buf.writeUInt32BE(counter & 0xffffffff, 4);
  const hmac = crypto.createHmac('sha1', key).update(buf).digest();
  const offset = hmac[hmac.length - 1] & 0x0f;
  const code =
    ((hmac[offset] & 0x7f) << 24) |
    ((hmac[offset + 1] & 0xff) << 16) |
    ((hmac[offset + 2] & 0xff) << 8) |
    (hmac[offset + 3] & 0xff);
  return (code % 1_000_000).toString().padStart(6, '0');
}

function currentStep(timestampMs: number = Date.now()): number {
  return Math.floor(timestampMs / 1000 / 30);
}

/** Generate the TOTP at a given timestamp (tests + script use this). */
function generateTotp(base32Secret: string, timestampMs = Date.now()): string {
  return hotpAt(base32Secret, currentStep(timestampMs));
}

/**
 * Verify a user-supplied token with a ±1 step drift window.
 * Returns the RFC 6238 step at which the token matched, or null if no
 * step in the window matches. The step is used by the caller to reject
 * replays — once a step has been accepted, subsequent attempts with a
 * step value ≤ last_accepted_step are refused even if the code is still
 * cryptographically valid within its 30-second lifetime.
 */
function verifyTotp(base32Secret: string, token: string): number | null {
  if (!/^\d{6}$/.test(token)) return null;
  const now = Date.now();
  const base = currentStep(now);
  for (const drift of [-1, 0, 1]) {
    const step = base + drift;
    if (timingSafeEq(hotpAt(base32Secret, step), token)) return step;
  }
  return null;
}

function timingSafeEq(a: string, b: string): boolean {
  const aBuf = Buffer.from(a);
  const bBuf = Buffer.from(b);
  if (aBuf.length !== bBuf.length) return false;
  return crypto.timingSafeEqual(aBuf, bBuf);
}

/** Build an otpauth:// URI that Google Authenticator / 1Password parse. */
function buildOtpAuthUri(issuer: string, account: string, secret: string): string {
  const label = encodeURIComponent(`${issuer}:${account}`);
  const params = new URLSearchParams({
    secret,
    issuer,
    algorithm: 'SHA1',
    digits: '6',
    period: '30',
  });
  return `otpauth://totp/${label}?${params.toString()}`;
}

export interface TotpEnrollment {
  secret: string;
  otpauthUrl: string;
  qrDataUrl: string;
  label: string;
}

export class TotpService {
  constructor(private knex: Knex, private issuer = 'Tellus') {}

  async isEnabled(keycloakSub: string): Promise<boolean> {
    const row = await this.knex('user_totp_secrets')
      .where({ keycloak_sub: keycloakSub, verified: true })
      .first();
    return !!row;
  }

  async startEnrollment(keycloakSub: string, accountLabel: string): Promise<TotpEnrollment> {
    const secret = generateBase32Secret();
    const label = `${this.issuer}:${accountLabel}`;
    const otpauthUrl = buildOtpAuthUri(this.issuer, accountLabel, secret);
    const qrDataUrl = await qrcode.toDataURL(otpauthUrl);

    await this.knex('user_totp_secrets')
      .insert({
        keycloak_sub: keycloakSub,
        label,
        secret,
        verified: false,
      })
      .onConflict('keycloak_sub')
      .merge({
        label,
        secret,
        verified: false,
        verified_at: null,
        created_at: new Date(),
      });

    return { secret, otpauthUrl, qrDataUrl, label };
  }

  async verifyEnrollment(keycloakSub: string, code: string): Promise<void> {
    const row = await this.knex('user_totp_secrets')
      .where({ keycloak_sub: keycloakSub })
      .first();
    if (!row) {
      throw new AppError('No enrollment in progress', 400, 'NO_ENROLLMENT');
    }
    const step = verifyTotp(row.secret, code);
    if (step === null) {
      throw new AppError('Incorrect TOTP code', 400, 'INVALID_CODE');
    }
    await this.knex('user_totp_secrets')
      .where({ keycloak_sub: keycloakSub })
      .update({
        verified: true,
        verified_at: new Date(),
        last_accepted_step: step,
      });
  }

  /**
   * Verify a TOTP code AND enforce one-time use within the 30-second
   * window by comparing against last_accepted_step. A code is rejected
   * if its matching step is ≤ the last accepted step — this blocks an
   * attacker who captures a code and replays it during the same step.
   */
  async verifyCode(keycloakSub: string, code: string): Promise<boolean> {
    const row = await this.knex('user_totp_secrets')
      .where({ keycloak_sub: keycloakSub, verified: true })
      .first();
    if (!row) return false;
    const step = verifyTotp(row.secret, code);
    if (step === null) return false;
    if (step <= Number(row.last_accepted_step ?? 0)) {
      // Replay — code cryptographically valid, already consumed.
      return false;
    }
    await this.knex('user_totp_secrets')
      .where({ keycloak_sub: keycloakSub })
      .update({ last_accepted_step: step });
    return true;
  }

  async disable(keycloakSub: string): Promise<void> {
    await this.knex('user_totp_secrets').where({ keycloak_sub: keycloakSub }).delete();
  }
}

let singleton: TotpService | null = null;
export function getTotpService(knex: Knex): TotpService {
  if (!singleton) {
    singleton = new TotpService(knex, process.env.TELLUS_TOTP_ISSUER || 'Tellus');
  }
  return singleton;
}

// Expose the low-level helpers so tests can generate a real TOTP code
// against a known base32 secret without a second installation step.
export const _totpHelpers = { generateBase32Secret, generateTotp, verifyTotp, buildOtpAuthUri };

// ---------------------------------------------------------------------
// Two-step /auth/login challenge store (parks Keycloak tokens between
// the password step and the MFA step).
// ---------------------------------------------------------------------

export async function saveMfaChallenge(
  knex: Knex,
  params: {
    id: string;
    keycloakSub: string;
    accessToken: string;
    refreshToken?: string;
    methods: string[];
    ttlSeconds: number;
  },
): Promise<void> {
  await knex('auth_mfa_challenges').insert({
    id: params.id,
    keycloak_sub: params.keycloakSub,
    access_token: params.accessToken,
    refresh_token: params.refreshToken,
    methods: params.methods,
    expires_at: new Date(Date.now() + params.ttlSeconds * 1000),
  });
}

export const MFA_MAX_ATTEMPTS = 5;
/** Sliding-window per-account budget — 20 failures per rolling hour. */
export const MFA_BUDGET_FAILURES = 20;
export const MFA_BUDGET_WINDOW_MS = 60 * 60 * 1000;

/**
 * Sliding-window rate limiter. Returns true if the caller is still
 * under the failure budget, false once they've exceeded it. The row
 * is upserted on every failure; success calls should reset it via
 * resetMfaBudget() so a successful login doesn't carry stale
 * counters into the next hour.
 */
export async function registerMfaFailure(
  knex: Knex,
  keycloakSub: string,
): Promise<{ blocked: boolean; retryAt: Date | null }> {
  return knex.transaction(async (trx) => {
    const row = await trx('mfa_attempt_budget')
      .where({ keycloak_sub: keycloakSub })
      .forUpdate()
      .first();
    const now = new Date();
    if (!row) {
      await trx('mfa_attempt_budget').insert({
        keycloak_sub: keycloakSub,
        window_start: now,
        failed_count: 1,
      });
      return { blocked: false, retryAt: null };
    }
    const windowStart = new Date(row.window_start);
    // Slide the window forward if the oldest failure fell out of range.
    if (now.getTime() - windowStart.getTime() >= MFA_BUDGET_WINDOW_MS) {
      await trx('mfa_attempt_budget').where({ keycloak_sub: keycloakSub }).update({
        window_start: now,
        failed_count: 1,
      });
      return { blocked: false, retryAt: null };
    }
    const nextCount = Number(row.failed_count ?? 0) + 1;
    await trx('mfa_attempt_budget').where({ keycloak_sub: keycloakSub }).update({ failed_count: nextCount });
    if (nextCount > MFA_BUDGET_FAILURES) {
      const retryAt = new Date(windowStart.getTime() + MFA_BUDGET_WINDOW_MS);
      return { blocked: true, retryAt };
    }
    return { blocked: false, retryAt: null };
  });
}

export async function resetMfaBudget(knex: Knex, keycloakSub: string): Promise<void> {
  await knex('mfa_attempt_budget').where({ keycloak_sub: keycloakSub }).delete();
}

export async function isMfaBudgetExhausted(
  knex: Knex,
  keycloakSub: string,
): Promise<{ blocked: boolean; retryAt: Date | null }> {
  const row = await knex('mfa_attempt_budget').where({ keycloak_sub: keycloakSub }).first();
  if (!row) return { blocked: false, retryAt: null };
  const windowStart = new Date(row.window_start);
  if (Date.now() - windowStart.getTime() >= MFA_BUDGET_WINDOW_MS) {
    return { blocked: false, retryAt: null };
  }
  if (Number(row.failed_count ?? 0) > MFA_BUDGET_FAILURES) {
    return { blocked: true, retryAt: new Date(windowStart.getTime() + MFA_BUDGET_WINDOW_MS) };
  }
  return { blocked: false, retryAt: null };
}

/**
 * Load an in-flight MFA challenge and atomically increment its attempt
 * counter. Returns null if the challenge is missing, expired, or has
 * burned through MFA_MAX_ATTEMPTS — the caller treats all three cases
 * as MFA_CHALLENGE_INVALID. A successful verify path should follow
 * this with consumeMfaChallenge() so the row is deleted, not reused.
 */
export async function loadMfaChallenge(
  knex: Knex,
  id: string,
): Promise<{
  keycloakSub: string;
  accessToken: string;
  refreshToken: string | null;
  methods: string[];
  attempts: number;
} | null> {
  return knex.transaction(async (trx) => {
    const row = await trx('auth_mfa_challenges').where({ id }).forUpdate().first();
    if (!row) return null;
    if (new Date(row.expires_at) < new Date()) {
      await trx('auth_mfa_challenges').where({ id }).delete();
      return null;
    }
    const attempts = Number(row.attempts ?? 0) + 1;
    if (attempts > MFA_MAX_ATTEMPTS) {
      await trx('auth_mfa_challenges').where({ id }).delete();
      return null;
    }
    await trx('auth_mfa_challenges').where({ id }).update({ attempts });
    return {
      keycloakSub: row.keycloak_sub,
      accessToken: row.access_token,
      refreshToken: row.refresh_token ?? null,
      methods: row.methods ?? [],
      attempts,
    };
  });
}

/**
 * Read-only load of an in-flight MFA challenge — verifies the row
 * exists and has not expired WITHOUT incrementing the attempt counter.
 *
 * Used by /login/mfa/webauthn-options, which only needs the challenge's
 * user binding to build WebAuthn ceremony options — it is NOT an
 * authentication attempt and must NOT count against MFA_MAX_ATTEMPTS.
 *
 * Why this exists: an earlier version of the options endpoint called
 * loadMfaChallenge(), which increments the counter. That burned one of
 * the 5 brute-force slots every time the browser fetched options —
 * including every passkey RETRY and every DISMISSED OS prompt (options
 * fetched, ceremony cancelled, no assertion ever submitted). After 2-3
 * such events on the same challenge the counter exceeded
 * MFA_MAX_ATTEMPTS and the user was told to "Start over from the
 * sign-in screen" even though they had never submitted a real
 * assertion. The actual verify (/login/mfa) still calls
 * loadMfaChallenge() — that is the only call site that should burn a
 * slot, because it is the only call site that actually attempts a
 * second factor.
 *
 * No transaction / FOR UPDATE here: there is no write, so there is no
 * concurrency hazard with the incrementing loadMfaChallenge() path.
 * Expired rows are still cleaned up so the caller sees the same
 * "challenge gone" signal loadMfaChallenge() returns.
 */
export async function peekMfaChallenge(
  knex: Knex,
  id: string,
): Promise<{
  keycloakSub: string;
  accessToken: string;
  refreshToken: string | null;
  methods: string[];
  attempts: number;
} | null> {
  const row = await knex('auth_mfa_challenges').where({ id }).first();
  if (!row) return null;
  if (new Date(row.expires_at) < new Date()) {
    await knex('auth_mfa_challenges').where({ id }).delete();
    return null;
  }
  return {
    keycloakSub: row.keycloak_sub,
    accessToken: row.access_token,
    refreshToken: row.refresh_token ?? null,
    methods: row.methods ?? [],
    attempts: Number(row.attempts ?? 0),
  };
}

export async function consumeMfaChallenge(knex: Knex, id: string): Promise<void> {
  await knex('auth_mfa_challenges').where({ id }).delete();
}

/**
 * Background sweeper — deletes every expired MFA challenge and
 * WebAuthn challenge row in one pass. Called from the server bootstrap
 * via setInterval so the short-lived tables never grow without bound.
 */
export async function purgeExpiredAuthChallenges(knex: Knex): Promise<{ mfa: number; webauthn: number }> {
  const mfa = await knex('auth_mfa_challenges').where('expires_at', '<', new Date()).delete();
  const webauthn = await knex('user_webauthn_challenges')
    .where('expires_at', '<', new Date())
    .delete();
  return { mfa, webauthn };
}

export function newMfaChallengeId(): string {
  return crypto.randomBytes(32).toString('hex');
}
