{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tellus-tenant.fullname" . }}-config
  namespace: {{ include "tellus-tenant.namespace" . }}
  labels:
    {{- include "tellus-tenant.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.configMap.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
