{{- if and .Values.podDisruptionBudget.enabled (or (gt (int .Values.replicaCount) 1) .Values.autoscaling.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tellus-tenant.fullname" . }}
  namespace: {{ include "tellus-tenant.namespace" . }}
  labels:
    {{- include "tellus-tenant.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "tellus-tenant.selectorLabels" . | nindent 6 }}
{{- end }}
