/**
 * Standard error codes used across the application.
 *
 * Each code is a unique string identifier that allows clients to
 * programmatically handle specific error conditions.
 */
export const ERROR_CODES = {
  // -- Authentication & Authorization --
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // -- Validation --
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_UUID: 'INVALID_UUID',
  INVALID_COLUMNS: 'INVALID_COLUMNS',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // -- Resource Errors --
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  COLUMN_NOT_FOUND: 'COLUMN_NOT_FOUND',
  VERSION_NOT_FOUND: 'VERSION_NOT_FOUND',
  VERSION_FILE_MISSING: 'VERSION_FILE_MISSING',

  // -- Dataset Errors --
  DATASET_NOT_READY: 'DATASET_NOT_READY',
  DATASET_PROCESSING: 'DATASET_PROCESSING',
  PARSE_ERROR: 'PARSE_ERROR',
  DUPLICATE_DATASET: 'DUPLICATE_DATASET',

  // -- Upload Errors --
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  LIMIT_FILE_SIZE: 'LIMIT_FILE_SIZE',
  LIMIT_FILE_COUNT: 'LIMIT_FILE_COUNT',
  LIMIT_UNEXPECTED_FILE: 'LIMIT_UNEXPECTED_FILE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  ZIP_TOO_LARGE: 'ZIP_TOO_LARGE',
  INVALID_ZIP: 'INVALID_ZIP',
  ZIP_EXTRACTION_FAILED: 'ZIP_EXTRACTION_FAILED',

  // -- Rate Limiting --
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // -- Server Errors --
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SHUTTING_DOWN: 'SHUTTING_DOWN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
