#!/usr/bin/env tsx
// ---------------------------------------------------------------------------
// Generate openapi/connectivity.{yaml,json} from the Zod contracts in
// src/services/connectivity/openapi.ts.
//
// Both forms are emitted so:
//   - The YAML is human-friendly for code-review (the canonical artifact).
//   - The JSON is what openapi-typescript / frontend tooling consumes
//     directly without a YAML dependency.
//
// Usage:
//   npm run generate:openapi:connectivity
//   # or:
//   tsx scripts/generate-openapi-connectivity.ts
//
// CI gate: run this script, then `git diff --exit-code openapi/` — if the
// emitted YAML drifts from the committed copy, fail the build. See
// tests/connectivity/b1.openapi-emission.test.ts for the in-process check.
// ---------------------------------------------------------------------------

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { buildOpenApiDocument } from "../src/services/connectivity/openapi";

function toYaml(value: unknown, indent = 0): string {
  // Minimal, deterministic YAML emitter — no escaping of edge-cases beyond
  // what OpenAPI uses (strings, numbers, booleans, arrays, objects, null).
  // Sufficient because the input is a typed OpenAPI document with no exotic
  // characters in keys; values that are exotic get quoted.
  const pad = "  ".repeat(indent);
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean" || typeof value === "number") {
    return String(value);
  }
  if (typeof value === "string") {
    if (
      value === "" ||
      /^[\s\-?:>|*&!%@`'"#]/.test(value) ||
      /[\n:]/.test(value) ||
      /^(true|false|null|yes|no|on|off)$/i.test(value) ||
      /^[+-]?\d/.test(value)
    ) {
      return JSON.stringify(value);
    }
    return value;
  }
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return value
      .map((v) => {
        const rendered = toYaml(v, indent + 1);
        if (typeof v === "object" && v !== null) {
          // Object members render with leading newline; first key gets the dash.
          const lines = rendered.split("\n");
          return `${pad}- ${lines[0].trimStart()}\n${lines
            .slice(1)
            .map((l) => `${pad}  ${l.replace(/^ {2}/, "")}`)
            .join("\n")}`.replace(/\n$/, "");
        }
        return `${pad}- ${rendered}`;
      })
      .join("\n");
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return "{}";
    return entries
      .map(([k, v]) => {
        const key = /^[A-Za-z_][A-Za-z0-9_-]*$/.test(k) ? k : JSON.stringify(k);
        if (v === null || v === undefined) return `${pad}${key}: null`;
        if (Array.isArray(v) || (typeof v === "object" && v !== null)) {
          const child = toYaml(v, indent + 1);
          if (child === "[]" || child === "{}") return `${pad}${key}: ${child}`;
          return `${pad}${key}:\n${child}`;
        }
        return `${pad}${key}: ${toYaml(v, 0)}`;
      })
      .join("\n");
  }
  return JSON.stringify(value);
}

async function main(): Promise<void> {
  const doc = buildOpenApiDocument();
  const outDir = resolve(__dirname, "..", "openapi");
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }
  const yamlPath = resolve(outDir, "connectivity.yaml");
  const jsonPath = resolve(outDir, "connectivity.json");
  const yamlContent =
    "# AUTO-GENERATED by scripts/generate-openapi-connectivity.ts. DO NOT EDIT.\n" +
    "# Regenerate via: npm run generate:openapi:connectivity\n" +
    toYaml(doc) +
    "\n";
  const jsonContent = JSON.stringify(doc, null, 2) + "\n";
  writeFileSync(yamlPath, yamlContent, "utf8");
  writeFileSync(jsonPath, jsonContent, "utf8");
  // eslint-disable-next-line no-console
  console.log(`wrote ${yamlPath}`);
  // eslint-disable-next-line no-console
  console.log(`wrote ${jsonPath}`);
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
